### PR TITLE
Add option to pass yaml object instead of path

### PR DESCRIPTION
**Pull request by GiladShoham**

### CODE REVIEW

**Comment by GiladShoham** [comment]
This pull request is coming along with this pull request: https://github.com/apigee-127/swagger-tools/pull/253

**Comment by theganyo** [comment]
Hey Gilad,

Unfortunately, your PR breaks the build, so I can't accept it presently. Also, all functions must include unit tests to ensure they are operating correctly.

But first, can you also explain why the changes in functionality you are proposing in this and the related PRs are necessary?

Thanks!
Scott

**Comment by GiladShoham** [comment]
Hi,
Thx for your response.

My yaml is separated to different files (because i have a lot of API, and i can't put them all in one file).
I used this technique http://azimi.me/2015/07/16/split-swagger-into-smaller-files.html to seperate the yaml parts to different files and i'm concatenating them in run time using the code in the end of this post.
because my yaml is loaded in runtime i have to somehow pass it to swagger runner and i can't just pass a path to a file.
i started to create an example for advanced using of swagger-node using swagger-express-mw (which uses this technique and also separate the controller to different location (like i have in my real project) and more stuff.
you can see my example here (it's in progress so no documentation yet but it's pretty easy to under stand. and it won't work with your version of runner, but only if you use my forked version and also my forked version of swagger-tools)
https://github.com/GiladShoham/SwaggerExpressAdvancedExample

about the tests, it will be great if you can help me with this, if not, ill try to fix them in a few days.

Thx a lot.

p.s in this example you can also see the reason beyond the https://github.com/theganyo/swagger-node-runner/pull/8

**Comment by theganyo** [comment]
The latest version of swagger-node-runner has been updated to the latest swagger-node module - which should resolve your refs without you having to concatenate the yaml files yourself. This should solve most of your problem, I believe?

**Comment by GiladShoham** [comment]
Hi,
I will check this, but i still think it a great feature because of 2 reasons:
1. you can never know where is the swagger of the user come from, maybe someone generate it from other spec in run time or someone can retrieve it from his DB or bring it in run time via HTTP from another server, so it's great option to pass it in.
2. i have also added the option to pass different path of the yaml file, which is also a great feature because right now the yaml have to be in specific path in the project.

Last thing, maybe it worth to ask the people who maintain the swagger node to make sure that the swagger-express-mw is using the last version of the runner.

Have a nice day

**Comment by theganyo** [comment]
FYI, this should work in the new beta: https://github.com/swagger-api/swagger-node/issues/294

set: config.swagger = { your object }

**Pull request closed without merging**
