### PR TITLE
use request logger whenever it's available

### PR DESCRIPTION
**Pull request by osher**
I'm still not sure about line 43.

I did not touch it - but I feel there's a problem there - for the least of it, it should be `next(err)` or maybe even `next(err2)`...

### CODE REVIEW

**Comment by theganyo** [comment]
This is interesting, but I haven't seen putting a "log" attribute on request & response as a convention. Is this commonly used?

**Comment by osher** [comment]
yes.
Express does it, Restify does it, I'm not sure about hapi - but I'm quire positive there is a plugin that does.

I'm on a work station now, I'll get it working shortly

**Comment by osher** [comment]
um.. - I need a point in the right direction regarding the last stage of error handling.

If I get it right:
 - calling `next(err)` resorts to the default error handling of the used framework, which is usually a rude 500 page with HTML content.
 - the handler is there to ensure the resopnse is sent as `application/json`
Therefore
 - the handler should call `next(null, formattedJSONBody)`

so I adjust my implementation following that understanding, I'd appreciate if you can confirm I'm right.

Also - we could use `fittingDef` to customize the output more - I'd love any inputs on that...

**Comment by osher** [comment]
re. how common that is:
restify - out of the box (http://restify.com/#log)
hapijs - out of the box (http://hapijs.com/tutorials/logging)
express  - middleware that provides you with `req.log` (which I only found about today, when I worked with express we did it ourselves, it's just a single silly function that mounts req.log...)

**Comment by theganyo** [comment]
Fantastic. Yes, I agree with your design. This looks like a great patch. Thanks for your work on it!

Are you finished or do you want to add anything else? (You mentioned configuration above... not sure what you might have in mind.)

**Comment by osher** [comment]
If you like it as it is and don't see any reason to provide output customization - then lets go.

For honesty's sake - I found one more frequent habit I do not cover common among express programmers:

`req.app.log`.

Would you like to support it?
if yes - can it be in a later PR?

**Comment by osher** [comment]
Ok. done. I did it too.
I also arranged the order of checks by what I believe to be the most commonly used.

I would also update the README.md, but it looks you're not documenting there anything...
where should I doc it? I see that the WIKI is empty too :open_mouth:

**Comment by osher** [comment]
mm. one more thing

If you're aware on the performance penalty of just *entering* a try block - then you may want to consider starting the try at line 39 (or even `try{}` only the `JSON.stringify`).

let me know what you think

**Comment by theganyo** [comment]
Documentation had been generally left to the swagger project that uses this one. (Although that probably needs to change as that project is no longer in sync with what's happening here.) That said, I've been documenting changes in the [release notes](https://github.com/theganyo/swagger-node-runner/releases).

Re: Optimization, yes, we could move the exit conditions (lines 27-38) to before the try block. Also, it appears that you could move your log assignment down to the catch block to ensure it's only defined when used.

**Comment by osher** [comment]
So wierd. It fails test. We might have uncovered something else here, but this should belong to another issue.
The problematic line is the actual call to `next(err)` in 
```
   if (context.statusCode === 500 && !fittingDef.handle500Errors) { return next(err); }
```

I added a `//TODO` comment and left it in the `try{}` block

**Comment by theganyo** [comment]
Thanks!

**Comment by osher** [comment]
wassup here? any reason for delay?

**Comment by osher** [comment]
oups. Ah! great!!!

**Pull request merged**
