### PR TITLE
fix sails status code 4xx instead of 500 on non allowed verb (issue #29)

### PR DESCRIPTION
**Pull request by cgalibern**
This will use api/responses/badRequest.js to return 400 statusCode.

If project want exact status code, api/responses/badRequest.js line
function badRequest(data, options) {
...
  res.status(400);
...
can be changed with exact status code from data.statusCode

### CODE REVIEW

**Comment by theganyo** [comment]
Great catch. Thanks!

**Comment by theganyo** [comment]
Oops. Actually, I think I accepted that too quickly. I believe "response.status" only applies to Sails, correct?

**Comment by cgalibern** [comment]
@theganyo yes it is used into sails. negotiate() to decide some default response: https://github.com/balderdashy/sails/blob/master/lib/hooks/responses/defaults/negotiate.js#L40

**Comment by cgalibern** [comment]
I have tested with previous swagger-node-runner: version 0.5.13, the bug was not present there, but api return 200 instead of 405

-  connect    =>  HTTP/1.1 405 Method Not Allowed, correct response body
- api             =>  HTTP/1.1 200 OK,                            correct response body
- express     =>  HTTP/1.1 405 Method Not Allowed, correct response body
- restify        =>  HTTP/1.1 405 Method Not Allowed, correct response body
- sails          =>  HTTP/1.1 405 Method Not Allowed, correct response body

**Comment by theganyo** [comment]
Great, thanks. I'll just add a comment on it.

**Comment by cgalibern** [comment]
@theganyo  thanks

**Pull request merged**
