### PR TITLE
Allow user to specify location of swagger file

### PR DESCRIPTION
**Pull request by wblankenship**

### CODE REVIEW

**Comment by GiladShoham** [comment]
Hi,
i have added an option to specify yaml path or even pass the yaml object it self.
see pw #7 .
I have to write some testing and fix some of the existing testing in order to merge it.
if you can give a hand in the testing, we can get both features at once.

Thx.

**Comment by drissamri** [comment]
I was looking for this option as well, would be nice if this could be merged.

**Comment by theganyo** [comment]
FYI: I'm working on a new version that will have both of these included.

**Comment by wblankenship** [comment]
Thanks @theganyo. I've just been using my branch for local dev.

**Comment by theganyo** [comment]
FYI, this should work in the new beta: https://github.com/swagger-api/swagger-node/issues/294

**Pull request closed without merging**
